### ISSUE TITLE
缺少文件 word_vec_300.bin

### ISSUE THREAD

**Issue by SoarAnyway** [liuhuanyong/MultiSenseDetection#2]
FileNotFoundError: [Errno 2] No such file or directory: 'word_vec_300.bin'

**Comment by consolexinhun** [comment]
这个文件是需要自己下载的，网上应该都能够找到，大小在1G左右，需要的可以email我(m18890306195@163.com)

**Comment by consolexinhun** [comment]
这个代码在windows上跑有可能会出小问题，在加载词向量部分`for line in open(embedding_path)`，会说编码错误，改成UTF-8读取就行了`for line in open(embedding_path, 'r', encoding='UTF-8')`

**Comment by SoarAnyway** [comment]
> 这个代码在windows上跑有可能会出小问题，在加载词向量部分`for line in open(embedding_path)`，会说编码错误，改成UTF-8读取就行了`for line in open(embedding_path, 'r', encoding='UTF-8')`

好的，谢谢

**Comment by wallon-ai** [comment]
你好，请问一下"word_vec_300.bin"是自己训练的吗

**Comment by SoarAnyway** [comment]
> 你好，请问一下"word_vec_300.bin"是自己训练的吗

这个在网上可以下载到

**Comment by wallon-ai** [comment]
这个文件适用于所有问题吗？针对自己的业务需要单独训练生成相应的词向量吗？

**Comment by SoarAnyway** [comment]
> 这个文件适用于所有问题吗？针对自己的业务需要单独训练生成相应的词向量吗？

是通用的

**Comment by wallon-ai** [comment]
> > 这个文件适用于所有问题吗？针对自己的业务需要单独训练生成相应的词向量吗？
> 
> 是通用的

好的，多谢！

**Comment by wallon-ai** [comment]
这个文件适用于所有问题吗？针对不同的业务需要单独训练生成这个文件吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "SoarAnyway"<notifications@github.com&gt;; 
发送时间: 2020年12月17日(星期四) 下午4:29
收件人: "liuhuanyong/WordMultiSenseDisambiguation"<WordMultiSenseDisambiguation@noreply.github.com&gt;; 
抄送: "11月的尾巴～"<2901699473@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [liuhuanyong/WordMultiSenseDisambiguation] 缺少文件 word_vec_300.bin (#2)





  
你好，请问一下"word_vec_300.bin"是自己训练的吗
  
这个在网上可以下载到
